name: Run Tests

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 6,14,22 * * *"
env:
  CYPRESS_STUDENT1_PASSWORD: ${{ secrets.CYPRESS_STUDENT1_PASSWORD }}
  CYPRESS_TEACHER1_PASSWORD: ${{ secrets.CYPRESS_TEACHER1_PASSWORD }}
  CYPRESS_MANAGER1_PASSWORD: ${{ secrets.CYPRESS_MANAGER1_PASSWORD }}
  CYPRESS_ADMIN1_PASSWORD: ${{ secrets.CYPRESS_ADMIN1_PASSWORD }}
  REACT_APP_AWS_REGION: eu-west-3

  API_KEY: ${{ secrets.API_KEY }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure prod AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REACT_APP_AWS_REGION }}
      - run: sh ./initNpmrc.sh hei-store npm-hei-school 088312068315

      - name: Configure preprod AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REACT_APP_AWS_REGION }}
          unset-current-credentials: true
      - run: sh ./initNpmrc.sh hei-store npm-hei-lab 057045785189

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run:  npm run --spec cypress/e2e/authentification.cy.js

      - name: Send status to Instatus
        if: ${{ (success() || failure()) && github.event_name == 'schedule' }}
        run: |
          trigger=$(if [ '${{ job.status }}' == 'failure' ]; then echo 'down'; else echo 'up'; fi)
          echo "Trigger status is: $trigger"

          curl -X POST "${{ vars.AUTHENTIFICATION_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d "{\"trigger\": \"$trigger\"}"